#ifndef TESTBENCHLIBRARY_GLOBAL_H
#define TESTBENCHLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTBENCHLIBRARY_LIBRARY)
#define TESTBENCHLIBRARY_EXPORT Q_DECL_EXPORT
#else
#define TESTBENCHLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTBENCHLIBRARY_GLOBAL_H
